version: "3.9"

services:
  api:
    build: .
    ports:
      - "8005:8005"
    env_file: .env
    volumes:
      - ./models_artifacts:/app/models_artifacts
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
      mlflow:
        condition: service_started
      redis:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  train:
    build: .
    command: python -m src.training.train
    env_file: .env
    volumes:
      - ./models_artifacts:/app/models_artifacts
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
      mlflow:
        condition: service_started
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.0
    ports:
      - "5005:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://pm:pmpass@postgres:5432/pm_fault_db
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    command: >
      mlflow server
      --backend-store-uri postgresql://pm:pmpass@postgres:5432/pm_fault_db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pm
      POSTGRES_PASSWORD: pmpass
      POSTGRES_DB: pm_fault_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pm -d pm_fault_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
  mlflow_artifacts:
